format = """
[╭](fg:current_line)\
$os\
$username\
$hostname\
$directory\
$git_branch\
$fill\
$line_break\
$character\
"""

palette = 'tokyonight'
add_newline = true

[palettes.tokyonight]
foreground = '#a9b1d6'
background = '#1a1b26'
current_line = '#44475A'  # Kept original value as requested
primary = '#16161e'
box = '#292e42'
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
orange = '#ff9e64'
pink = '#f7768e'
purple = '#bb9af7'
red = '#f7768e'
yellow = '#e0af68'

[os]
format = '[\[$symbol btw\]](fg:cyan)'
disabled = false

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = '󰣇'
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[directory]
format = '[─](fg:current_line)[\[  $path\]](fg:purple)'
home_symbol = "~" 

[username]
format = '[─](fg:current_line)[\[ $user](fg:blue)'
show_always = true

[hostname]
format = '[@](fg:blue)[$hostname\]](fg:blue)'
ssh_only = false

[git_branch]
format = '[─](fg:current_line)[\[$symbol $branch\]](fg:green)'
symbol = '󰘬'

[nodejs]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = '󰎙 '

[dotnet]
format = '[─](fg:current_line)[](fg:purple)[$symbol](fg:primary bg:purple)[](fg:purple bg:box)[ $tfm](fg:foreground bg:box)[](fg:box)'
symbol = ' .NET'

[python]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' python'

[fill]
symbol = ' '
style = 'fg:current_line'

[cmd_duration]
min_time = 500
format = '[─](fg:current_line)[](fg:orange)[ ](fg:primary bg:orange)[](fg:orange bg:box)[ $duration ](fg:foreground bg:box)[](fg:box)'

[shell]
format = '[─](fg:current_line)[](fg:blue)[ ](fg:primary bg:blue)[](fg:blue bg:box)[ $indicator](fg:foreground bg:box)[](fg:box)'
unknown_indicator = 'shell'
powershell_indicator = 'powershell'
disabled = false

[time]
format = '[─](fg:current_line)[](fg:purple)[󰦖 ](fg:primary bg:purple)[](fg:purple bg:box)[ $time](fg:foreground bg:box)[](fg:box)'
time_format = '%H:%M'
disabled = false

[character]
format = """
[╰─$symbol](fg:current_line) """
success_symbol = '[>](fg:current_line)'
error_symbol = '[>](fg:current_line)'
